### ISSUE TITLE
Add strong name to assembly

### ISSUE THREAD

**Issue by jozefizso** [richardszalay/mockhttp#1]
Could you add a strong name to the MockHttp assembly, so it can be referenced from unit testing projects that are strongly named?

**Comment by richardszalay** [comment]
@jozefizso Is this still a requirement? Microsoft seems to be moving away from strong naming for third party components (https://github.com/dotnet/corefx/wiki/Strong-Naming), so I'd rather not go down that path unless it's really necessary.

**Comment by jozefizso** [comment]
No, it is not necessary to add strong name. Unit test projects does not have to be strongly named.

**Comment by oschwald** [comment]
I ran into a situation where this would be very useful. When you make your unit tests a friend assembly, using `InternalsVisibleTo`, with a strongly named assembly, your unit tests do need to strongly named.

**Comment by richardszalay** [comment]
I've decided to go ahead with this (gnrated, 3.5 years later) because:

1. It's highly unlikely that anyone will want to upgrade
2. There's not much in the way of "MockHttp extension" libraries, so binding redirects for netfx really aren't a problem

**Comment by richardszalay** [comment]
Released in 6.0.0
