### ISSUE TITLE
Add support for .NET Core

### ISSUE THREAD

**Issue by richardszalay** [richardszalay/mockhttp#10]
Since HttpClient is supported by aspnercore, it makes sense for mockhttp to work in that environment.

**Comment by dotnetshadow** [comment]
Hi I was wondering how the progress is going? I'm keen to get this working in a dnx project?

**Comment by richardszalay** [comment]
Hey, the dnx branch has it all set up I've yet to publish a nuget nightly for it. Feel to clone the branch and reference the source directly.

I'm unlikely to publish a real release before adpnet goes rc2 as the PCL targets are changing.

**Comment by dotnetshadow** [comment]
Oh ok thank you, I didn't realise the dnx branch was actually working good stuff :)

**Comment by richardszalay** [comment]
dotnetcore is supported via the dotnet5.4 moniker (a la aspnet5 rc1), but it will change to netstandard1.0 when rc2 is released.

Let me know how you get on, as I have no real aspnet 5 project to test with)

**Comment by dotnetshadow** [comment]
I was able to add it to my local asp.net 5 project using the local nuget method. I'm trying to work out how to add it as a dll assembly directly which I'm find hard to figure out.

I'm trying to follow this method:
http://stackoverflow.com/questions/29970854/how-do-you-add-references-to-locally-created-non-asp-net-5-dlls-to-an-asp-net-5

**Comment by dotnetshadow** [comment]
I decided to go via the local nuget route and the project seems to be working well great work

**Comment by am11** [comment]
Hi @richardszalay, GeoIP2 is being ported to .NET Core: https://github.com/maxmind/GeoIP2-dotnet/pull/60.

The UnitTests project in their solution consumes MockHttp package, so I have `#if`'d out the test file which was expecting mockhttp for NetCoreApp1.0.

Are there plans to release a beta with NetStandard1.4 like https://www.nuget.org/packages/MaxMind.Db/2.1.0-beta (which would not affect the stable version for major consumers)? Meanwhile, we, in the down-streams, would be able to consume that unstable preview version. Note that dotnet CLI RC2 is only [days away](https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/) and hopefully there would be no major / breaking change until then.

We have Travis (for OS X & Ubntu)) and AppVeyor scripts configured which downloads the latest version (daily builds) of CLI per job run. Those scripts are derivatives of ones proposed in dotnet/cli repo's issue 2113. If it helps, please feel free to reuse that community-evolved CI build script in your DNX (<del>dnx</del> .Net Core) branch. :)

**Comment by richardszalay** [comment]
@am11 Tbh, I've been holding off on a beta until RC2 was released. I like the idea of the nightly tools download as part of your build, but honestly the issue for me has been guidance around TFMs and unit testing. 

I've reached out to the dotnet guys again, but if you were to push your netcore branch to your github repo I'd be happy to use that as guidance.

**Comment by richardszalay** [comment]
.NET Core RC2 is now supported via netstandard1.1, in an alpha release - https://www.nuget.org/packages/RichardSzalay.MockHttp/1.3.0-netstandard-alpha2

I've also cleaned up support for Xamarin, and fixed a bug specific to the Xamarin Android platform. There should be no more assembly version conflict warnings on these platforms.

I've successfully run a basic example against the following targets using the new build:
* .NET Core RC2 Console App
* .NET 4.0 Console App
* .NET 4.5 Console App
* Xamarin Android Unit Test App
* UWP App

**Comment by richardszalay** [comment]
Released in 1.3.0
