### ISSUE TITLE
Adding Response Headers 

### ISSUE THREAD

**Issue by Pieeer1** [richardszalay/mockhttp#101]
This may be a supported method already, but if not should there be a way to simulate response headers? 
IE Respond(string mediaType, string content).WithHeaders(string key, string value) should return headers within the request.

**Comment by InteXX** [comment]
@Pieeer1 

What was your reason for closing this so quickly? Did you find a solution?

I ask because I have the same concern. I need to mock a 301 response code with a custom Location in the headers.
