### ISSUE TITLE
Matcher async support

### ISSUE THREAD

**Issue by sigurdhj** [richardszalay/mockhttp#105]
Hi.

Is there any chance of getting async support for the matchers? I.e

```
.With(async req =>
{
  var user = await myCustomSerializer.DeserializeAsync(await req.Content?.ReadAsStringAsync())
  return user.Name == "some name" && user.Addresses.First() == "some address";
})
```

**Comment by richardszalay** [comment]
Assume your source stream isn't likely to actually to involve network streams (given that it's a test), you can simply do:

```
.With(async req =>
{
  var requestJson = req.Content?.ReadAsStringAsync().GetAawaiter.GetResult();
  var user = myCustomSerializer.DeserializeAsync(requestJson).GetAawaiter.GetResult();
  return user.Name == "some name" && user.Addresses.First() == "some address";
})
```

**Comment by richardszalay** [comment]
I'm going to close this issue in lieu of not hearing anything further from you. I'm happy to reopen if you have further information to provide.

**Comment by vidarkongsli** [comment]
Upgrading XUnit to 2.5 causes the following error 

> Assume your source stream isn't likely to actually to involve network streams (given that it's a test), you can simply do:
> 
> ```
> .With(async req =>
> {
>   var requestJson = req.Content?.ReadAsStringAsync().GetAawaiter.GetResult();
>   var user = myCustomSerializer.DeserializeAsync(requestJson).GetAawaiter.GetResult();
>   return user.Name == "some name" && user.Addresses.First() == "some address";
> })
> ```

Upgrading to XUnit 2.5 causes the following error message when blocking with `.GetAwaiter().GetResult();`: https://xunit.net/xunit.analyzers/rules/xUnit1031

In light of this, you might reconsider reopening this issue. Thanks.
