### ISSUE TITLE
PostAsync with When() returns NotFound - but only when an Expect() is also defined

### ISSUE THREAD

**Issue by dylanbeattie** [richardszalay/mockhttp#106]
Hello!

I'm having some issues using `MockHttpMessageHandler`; if I add an `Expect()` to my HTTP mock, then `When()` calls start returning a 404 not found. The only difference between these two tests is the `mockHttp.Expect()` line is commented out in one of them.

I've isolated the behaviour down to this pair of test cases, which hopefully demonstrate exactly what's happening:

```csharp
[Fact]
public async void This_Test_Will_Pass() {
  const int ID = 123;
  var mockHttp = new MockHttpMessageHandler();
  mockHttp.When(HttpMethod.Post, $"https://api.test/{ID}/bar").Respond(HttpStatusCode.Created);
  
  // The test will only pass if the following line is commented out
  // mockHttp.Expect(HttpMethod.Post, $"https://api.test/{ID}/foo").Respond(HttpStatusCode.Created);

  var httpClient = mockHttp.ToHttpClient();
  var response = await httpClient.PostAsync("https://api.test/123/bar", new StringContent(""));
  response.EnsureSuccessStatusCode();
}

[Fact]
public async void This_Test_Will_Fail() {
  const int ID = 123;
  var mockHttp = new MockHttpMessageHandler();
  mockHttp.When(HttpMethod.Post, $"https://api.test/{ID}/bar").Respond(HttpStatusCode.Created);

  // When the following line is uncommented, the test fails (NotFound instead of Created)
  mockHttp.Expect(HttpMethod.Post, $"https://api.test/{ID}/foo").Respond(HttpStatusCode.Created);
  
  var httpClient = mockHttp.ToHttpClient();
  var response = await httpClient.PostAsync("https://api.test/123/bar", new StringContent(""));
  response.EnsureSuccessStatusCode();
}
```

Am I missing something here? Changing the order in which I set up the `When` / `Expect` doesn't make any difference.

Thanks,

Dylan

**Comment by dylanbeattie** [comment]
OK, further investigation shows that this appears to be because I haven't actually called the Expect() yet:

```csharp
[Fact]
public async void This_Test_Will_Pass() {
  const int ID = 123;
  var mockHttp = new MockHttpMessageHandler();
  mockHttp.Expect(HttpMethod.Post, $"https://api.test/{ID}/foo").Respond(HttpStatusCode.Created);
  mockHttp.When(HttpMethod.Post, $"https://api.test/{ID}/bar").Respond(HttpStatusCode.Created);
  var httpClient = mockHttp.ToHttpClient();
  await httpClient.PostAsync("https://api.test/123/foo", new StringContent(""));
  var response = await httpClient.PostAsync("https://api.test/123/bar", new StringContent(""));
  response.EnsureSuccessStatusCode();
}
```

I'd assumed the fallback behaviour from `Expect` to `When` was an a per-URL-per-method basis, but it looks like what's actually happening is that as long as there are unsatisifed `Expect()` expectations, any call that would be handled by a `When` is going to return a `404 NotFound` - is that correct?

**Comment by dylanbeattie** [comment]
...and there's the bit of the docs that didn't make any sense until I'd found this out the hard way:

> but they won't match if there are any outstanding Request Expectations present (unless BackendDefinitionBehavior.Always is specified). If no Request Expectations match, Fallback will be used.

**Comment by dylanbeattie** [comment]
Would you be interested in a PR that would make the error message more explicit in this particular scenario? I realised it's covered in the documentation but I'd be happy to take a look at making the error message more descriptive so that other folks don't end up in the same situation I found myself in.

**Comment by mosoftwareenterprises** [comment]
I just bumped into the exact same problem @dylanbeattie . Thanks for the info, I can fix my issue now. Clearer docs would help here.

**Comment by richardszalay** [comment]
Happy to make things clearer, but could you elaborate on why the [When vs Expect](https://github.com/richardszalay/mockhttp#when-backend-definitions-vs-expect-request-expectations) and [Match Behavior](https://github.com/richardszalay/mockhttp#match-behavior) parts of the README aren't clear enough?

**Comment by richardszalay** [comment]
I'm going to close this ticket, but if you have time to elaborate on how the linked parts of the readme could be made clearer I'm happy to imprive the docs.
