### ISSUE TITLE
How do I simulate a thrown exception during a network request?

### ISSUE THREAD

**Issue by jeffcharles** [richardszalay/mockhttp#12]
I want to unit test a case where an `HttpException` is thrown by a call to perform a given request with `HttpClient`. Is there support in `mockhttp` to do this?

**Comment by richardszalay** [comment]
`Respond` has an overload takes a lambda. You should have no problems throwing an exception there.

**Comment by jeffcharles** [comment]
Makes sense. I may open a PR for adding an example to the docs for that.
