### ISSUE TITLE
Simulate httpClient Throwing an Exception (Feature Request)

### ISSUE THREAD

**Issue by camiller2** [richardszalay/mockhttp#13]
Add support to mock an httpClient throwing an exception.  Usage might be something like:

```c#
 _mockHttpMessageHandler.Expect(urlBase)
     .WithQueryString(string.Format(queryString, id))
     .ThrowsException(new Exception("HTTP call threw an exception."));
```

**Comment by richardszalay** [comment]
Is there any reason why https://github.com/richardszalay/mockhttp/issues/12 wouldn't work for you?

**Comment by camiller2** [comment]
That works perfectly, thanks!  I'll probably open a PR with a simple extension method to make this dead simple.
