### ISSUE TITLE
Multiple requests fail on version 7 when using Expect

### ISSUE THREAD

**Issue by mindaugasveblauskas** [richardszalay/mockhttp#131]
Hi, I've just noticed, that with version 7 you can't make more than one request when you configure with Expect method.
When you configure `Expect` you don't tell specifically how many times you expect this request to be sent. So I assume it should be any number of requests, just like it was on version 6, but it's not the case on version 7 anymore. Is that expected? Or did I miss something in the docs?

Sharing a code sample:

```[TestMethod]
public async Task TestMultipleRequests()
{
    var mockHttp = new MockHttpMessageHandler();

    mockHttp.Expect("http://localhost/api/user/*")
        .Respond(HttpStatusCode.Unauthorized);

    var client = mockHttp.ToHttpClient();

    await client.GetAsync("http://localhost/api/user/1234"); // Test passes
    // await client.GetAsync("http://localhost/api/user/1234"); // Uncomment this line and it will fail with RichardSzalay.MockHttp.MockHttpMatchException: Failed to match a mocked request for GET http://localhost/api/user/1234
}

**Comment by richardszalay** [comment]
This is the expected (no pun intended) behaviour. `Expect` sets up ordered mocks, so if you want it to match twice you need to call `Expect` twice.

Alternatively, if you just want to match regardless of the order use `When` instead.

**Comment by mindaugasveblauskas** [comment]
Thanks for a quick answer. But it was not mentioned anywhere in the release notes of v7?

**Comment by richardszalay** [comment]
The behaviour hasn't changed between v6-v7 (or from V1 honestly)

**Comment by richardszalay** [comment]
I'm going to close this ticket as I haven't heard back from you. Happy to continue discussion if you're still having issues though
