### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'RichardSzalay.MockHttp.RequestHandlerResult' to type 'System.String'

### ISSUE THREAD

**Issue by asanfilov** [richardszalay/mockhttp#136]
Would you please consider releasing a new version of your library that does not change HttpRequestMessage Options?

### Background
My company has .NET6 projects with unit tests that use RichardSzalay.MockHttp Version 6.0.0.
Updating to Version 7.0.0 causes dozens of our unit tests to fail when they execute this method (edited for brevity):  
```cs
public static async Task<HttpRequestMessage> CloneAsync(this HttpRequestMessage request)
{
  var clone = new HttpRequestMessage(request.Method, request.RequestUri);
  foreach (KeyValuePair<string, object> opt in request.Options)
  {
    //throws System.InvalidCastException: 
    //Unable to cast object of type 'RichardSzalay.MockHttp.RequestHandlerResult' to type 'System.String'.
    clone.Options.Set<string>(new HttpRequestOptionsKey<string>(opt.Key), (string)opt.Value);
  }
  return clone;
}
```

### Technical details 
- I have found this method in MockHttpMessageHandler:  
`internal static void SetHandlerResult(HttpRequestMessage request, RequestHandlerResult handlerResult)`  
which sets `RichardSzalay.MockHttp.RequestHandlerResult` as a value in HttpRequestMessage Properties (please see commit  
https://github.com/richardszalay/mockhttp/commit/bea35edbed7ece888f314eeae1b0ffb4a0e6108f)

- which will be reflected in the Options property key/values of the [HttpRequestMessage.cs](https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/System.Net.Http/src/System/Net/Http/HttpRequestMessage.cs) class:  
```cs HttpRequestMessage.cs
[Obsolete("HttpRequestMessage.Properties has been deprecated. Use Options instead.")]
public IDictionary<string, object?> Properties => Options;
```

### What I tried
- Commented out the call to `SetHandlerResult` in MockHttpMessageHandler  
in `private IMockedRequest FindHandler(HttpRequestMessage request)`  
and none of the RichardSzalay.MockHttp.Tests failed, so
- I re-built the RichardSzalay.MockHttp project and placed the updated RichardSzalay.MockHttp.dll file next to our unit test assembly, then re-ran our failing unit tests. They passed without encountering the System.InvalidCastException mentioned above.

**Comment by richardszalay** [comment]
Hi @asanfilov,

Is that CloneAsync method in MockHttp or your own code? It looks like it's casting all Options values to be a string, despite it being typed as a `Dictionary<string, object>`

I'd recommend adding a guard so that it doesn't attempt to copy non string values (or by handling it in some other way)

Otherwise you're likely to run into similar issues when other delegating handlers add their own options.

Richard

**Comment by asanfilov** [comment]
Hi @richardszalay 
Thanks for the quick feedback on the CloneAsync method implementation. Your observation regarding the casting of Options values to string types, despite their original definition as `Dictionary<string, object>`, was spot on. I have updated the code to:
`clone.Options.TryAdd(opt.Key, opt.Value)` 
as you suggested, and all unit tests are now green. Appreciate your help! I will close this issue.
