### ISSUE TITLE
Configure a delayed response

### ISSUE THREAD

**Issue by Skintkingle** [richardszalay/mockhttp#142]
Is there a way to delay a mocked response such that I can hold (probably with a way programmatically to "continue") the request. This would be super useful in testing flags that are set to indicate my ViewModels are correctly showing that they're busy when talking to a network.

Great mocking framework by the way. Really easy to use otherwise. :)

**Comment by Skintkingle** [comment]
Ignore this, I used a ManualResetEvent and a delegate to achieve this out-of-framework.

For anyone interested in the future, I did this:

        var flag = new ManualResetEvent(false);
        _mockHttpMessageHandler.When(HttpMethod.Get, "http://localhost/myApi").Respond(
            () =>
            {
                flag.WaitOne();
                var responseMessage = new HttpResponseMessage(HttpStatusCode.OK);
                responseMessage.Content = new StringContent("[]");
                return Task.FromResult(responseMessage);
            });
        var sut = CreateSut();
        var loadTask = sut.LoadAsync();

        Assert.That(sut.Loading, Is.True);
        flag.Set();
        await loadTask;
        Assert.That(sut.Loading, Is.False);

**Comment by richardszalay** [comment]
Nice! FYI, you could have also a [TaskCompletionSource](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcompletionsource-1?view=net-8.0)
