### ISSUE TITLE
Remove Profile111

### ISSUE THREAD

**Issue by richardszalay** [richardszalay/mockhttp#18]
According to [".NET Standard Library - PCL Compatibility"](https://docs.microsoft.com/en-us/dotnet/articles/standard/library#pcl-compatibility), netstandard1.1 is compatible with Profile111. 

That being the case, it should be fine to remove Profile111 from the build. The only thing I can see being an issue is it would be dropping support for NuGet 2.x (since it doesn't support the netstandard TFMs)

**Comment by richardszalay** [comment]
@onovotny reminded me that [NuGet 2.12 supports netstandard monikers](https://oren.codes/2016/06/23/portable-is-dead-long-live-netstandard/) so 111 can probably be safety dropped.

**Comment by onovotny** [comment]
Here's the NuGet team blog with the details: http://blog.nuget.org/20160627/Announcing-NuGet-3.5-Beta-2-and-2.12-RTM.html

**Comment by richardszalay** [comment]
I'll be removing this as part of the multi-targeting alignment #61 / 4.0

**Comment by richardszalay** [comment]
Released in 5.0.0
