### ISSUE TITLE
Project can't build on Mac OS due to NuGet outdated

### ISSUE THREAD

**Issue by akamud** [richardszalay/mockhttp#19]
When using Mac OS to build projects targeting .NET 4.5, you have a dependency on `System.Net.Http` version `4.0`, this causes a problem since  this package depends on NuGet version 3, which is not available yet on Xamarin Studio stable channel (will be supported in 6.1, but it is still [very early on preview](https://developer.xamarin.com/releases/studio/xamarin.studio_6.1/xamarin.studio_6.1/)), so you just can't build a project referencing `MockHttp`.

This is the error I get:
`2016-07-11T22:22:05.800Z: The 'System.Net.Http 4.0.0' package requires NuGet client version '3.0' or above, but the current NuGet version is '2.8.5.0'.`

Could .NET 4.5 also depend on `Microsoft.Net.Http` instead of `System.Net.Http`? Or is there any workaround for this?

**Comment by richardszalay** [comment]
Hi @akamud - am I correct in assuming you're targeting Mono here?

**Comment by richardszalay** [comment]
Try using mockhttp 1.2.2 as that uses Microsoft.Net.Http across the board. I switched to System.Net.Http in 1.3.0 on advice from some MS guys.

**Comment by akamud** [comment]
Hi, you are correct, I am using Mono.

I'll downgrade for now, thanks for the quick response!

**Comment by richardszalay** [comment]
No problem!
