### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by hassanahamed** [richardszalay/mockhttp#22]
i got the issue as follows:-
Could not load file or assembly 'RichardSzalay.MockHttp, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The bound assembly has a version that is lower than that of the request. (Exception from HRESULT: 0x80132000).

when i was working for windows phone it worked absolutely fine.
but when i was replicating the same functionality for windows 8, i got the above error.
can you please help me out on this.
thanks

**Comment by richardszalay** [comment]
I'm not able to reproduce this. Can you open your csproj and paste the HintPath for MockHttp?

**Comment by richardszalay** [comment]
Hi hassanahamed, any follow up on this?

**Comment by richardszalay** [comment]
Hi hassanahamed, I haven't heard any more from you on this issue so I'll close this issue. Please re-open it if you have any more information to add.
