### ISSUE TITLE
Headers in the response

### ISSUE THREAD

**Issue by Jericho** [richardszalay/mockhttp#25]
I there a way to specify headers in the response of a mocked request?

This is how I am currently mocking the response and specifying the content of the response but I can't figure out how to specify the headers
```
var mockHttp = new MockHttpMessageHandler();
mockHttp.Expect(HttpMethod.Get, "https://api.myvendor.com/v1/myendpoint")
	.With(request => request.Content == null)
	.Respond("application/json", "{'name' : 'This is a test'}");
```
The reason I'm asking is because the API is returning information in the header regarding throttling (such as how many calls I have left in the next X seconds, how long I should wait until my next call if I exceed max calls per second, etc.) and I want to unit test my code which handles these header items.

**Comment by richardszalay** [comment]
Sure, just create the response yourself:

```
var mockHttp = new MockHttpMessageHandler();
mockHttp.Expect(HttpMethod.Get, "https://api.myvendor.com/v1/myendpoint")
	.With(request => request.Content == null)
	.Respond(request =>
        {
            var response = new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent("{'name' : 'This is a test'}", Encoding.UTF8, "application/json")
            };

            // Adjust your response headers here

            return response;
        });
```

**Comment by Jericho** [comment]
Cool. That's easy! thanks for helping me.

**Comment by richardszalay** [comment]
No worries, glad it helped!
