### ISSUE TITLE
Check that no request was sent

### ISSUE THREAD

**Issue by Thaoden** [richardszalay/mockhttp#27]
As far as I understand it, I can use the `MockHttpHandler` to set up expectations that have to be met by my system under test, like "My SUT should make a call to this URL". Is there a way to check that _no_ request was made at all?

**Comment by richardszalay** [comment]
There's no built in assertion for that, but it would be easily enough to do:

```
int requestCount = 0;

mockHttp.When("*")
    .Respond(req =>
    {
        requestCount++;
        return new HttpResponseMessage(HttpStatusCode.NotFound);
    });

Assert.Equals(0, requestCount);
```

**Comment by Thaoden** [comment]
Sounds easy enough, indeed. Thanks!
