### ISSUE TITLE
Simulate delay or timeout?

### ISSUE THREAD

**Issue by denisz1** [richardszalay/mockhttp#29]
How can I simulate a network delay, or a timeout (where the response never arrives)?

I tried this but it doesn't work:

     client.Timeout = 1;
     mock.When("*").Respond(async () => { await Task.Delay(1000); return null; } );

**Comment by richardszalay** [comment]
When you say "it doesn't work" - what happens? Does it instantly return null? Returns 404 (ie. not matched)?

Could you try this intead?

```
client.Timeout = 1;
mock.Fallback.Respond(async () => { await Task.Delay(2000); return null; } );
````

**Comment by denisz1** [comment]
@richardszalay If `delay > timeout`, then I expect it would throw a `TokenCanceledException`.

But that doesn't happen. It performs the delay, then just continues as usual. Strange.

**Comment by richardszalay** [comment]
Interesting. I can reproduce your problem, but I'm not sure why it doesn't work - that should be handled by HttpClient. I'll have a look at the HttpClient source and see what I can find.

**Comment by richardszalay** [comment]
Ok, this was definitely a limitation in MockHttp. Thanks for catching it.

I've resolved this and included it in the 1.4.0 release, which has just been pushed to NuGet.

**Comment by denisz1** [comment]
Thanks, this is great, because now it throws so I know something has gone wrong.

But... it throws an `OperationCanceledException`. [Shouldn't it be a `TaskCanceledException`](http://stackoverflow.com/a/12901496/7059613) with `e.CancellationToken.IsCancellationRequested == false`?

**Comment by richardszalay** [comment]
MockHttp isn't throwing any specific exception, it's simply respond to the cancellation and bubbling it back up.

My understanding is that while `OperationCanceledException` is a base class of `TaskCanceledException`, it can still be thrown in it's own right by the Task infrastructure. Your domain code should definitely handle `OperationCanceledException`

**Comment by denisz1** [comment]
Okay that makes sense. MockHttp isn't in control of this part.
