### ISSUE TITLE
System.TypeLoadException when mocking response with status code other than 2xx 

### ISSUE THREAD

**Issue by SteffenGorenflo** [richardszalay/mockhttp#34]
I have the following test setup:

````c#
var mockHttp = new MockHttpMessageHandler();

mockHttp.Expect("/oauth/token/")
      .Respond(HttpStatusCode.OK, "application/json", "{'ok':true}");
````
This works fine, but when I set the response status code to `HttpStatusCode.Unauthorized` (for example), I get the following error:
````
System.TypeLoadException : Could not resolve type with token 01000090 (from typeref, class/assembly System.Net.HttpStatusDescription, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
````

I wonder if it might have something to do with the warning I get when using this library:
```
Warning: Assuming assembly reference 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f711d50a3a' used by 'RichardSzlalay.MockHttp' matches identity 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f711d50a3a' of 'System.Net.Http', you may need to supply runtime policy
```

Our REST-library is refit and I use the mock like:
````c#
var refitSettings = new RefitSettings {
       HttpMessageHandlerFactory = mockHttp
};

RestService.For<IBackendAPI>(baseURL, refitSettings);
````

**Comment by richardszalay** [comment]
Can you let me know what version of both .net and `System.Net.Http` you are targeting?

**Comment by SteffenGorenflo** [comment]
I use the following settings:
``
  <package id="System.Net.Http" version="4.3.2" targetFramework="net462" />
``

**Comment by richardszalay** [comment]
I'm unable to reproduce the issue. What kind of project are you testing (Console, ASP.NET, Xamarin Android, etc)? If you can provide a minimal reproducible sample I'm happy to look into it further.

The sample code below throws `Refit.ApiException: Response status code does not indicate success: 401`, which is what I would expect.

* Project type: Console
* Target Framework: .NET 4.6.2
* Dependencies:
  * System.Net.Http - 4.3.2
  * Refit - 3.1.0
  * RichardSzalay.MockHttp - 1.5.0

Code:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var mockHttp = new MockHttpMessageHandler();

        mockHttp.Expect("/oauth/token/")
                .Respond(HttpStatusCode.Unauthorized, "application/json", "{'ok':true}");

        var refitSettings = new RefitSettings
        {
            HttpMessageHandlerFactory = () => mockHttp
        };

        var backendApi = RestService.For<IBackendAPI>("http://localhost/", refitSettings);
        var result = backendApi.Auth().GetAwaiter().GetResult();
            

    }
}

public interface IBackendAPI
{
    [Get("/oauth/token/")]
    Task<BasicResponse> Auth();
}

public class BasicResponse
{
    public bool Ok { get; set; }
}
```

**Comment by SteffenGorenflo** [comment]
Thanks for the quick response. I wasn't able to look into it till now. 
 
I noticed that my unit test project (which has all the correct dependencies versions above) is testing my Core project which has the following Version: `PCL 4.6 - Profile151` 

Is this maybe the problem? I'm new to this .NET environment and maybe I mix somethings up.

Btw, that example of you is working with me as well.

**Comment by SteffenGorenflo** [comment]
Alright I fixed it. In my Test project there was somehow a reference to the System.Net.Http package with the assembly version "4.1.1.1". 

After removing this reference and changing it to the correct reference (.net framework 4.6.2) it worked.

To be specific: I changed  in `MyProject.UnitTests.csproj` the line 

```
<Reference Include="System.Net.Http">
    <HintPath>..\packages\System.Net.Http.4.3.2\lib\net46\System.Net.Http.dll</HintPath>
</Reference>
```
to 
```
<Reference Include="System.Net.Http" />
```
