### ISSUE TITLE
Remove dependency of Install-Package System.Net.Http nuget package

### ISSUE THREAD

**Issue by YehudahA** [richardszalay/mockhttp#36]
I have a project with a reference to System.Net.Http library. [From .NET assemblies, not the nuget package]

When I install the RichardSzalay.MockHttp package it installs also the System.Net.Http nuget package.
There is any way to remove this dependency?

[Sorry for my bad English]

**Comment by richardszalay** [comment]
Don't apologise, your English is perfect :)

You should just be able to remove the assembly reference to System.Net.Http and re-add the framework version, leaving all NuGet packages as-is.

References aren't re-configured when restoring packages, so you should only need to do it once.

**Comment by YehudahA** [comment]
But System.Net.Http has dependency on System.Security.Cryptography.X509Certificates and it has dpendnecy on other packages.

Every time when I update my nuget packages, is installs all those packages.

**Comment by richardszalay** [comment]
Since the `System.Net.Http` package is the more "official" (and frequently updated) HTTP client, I'm going to close this issue.

If you'd like to use MockHttp with the built in System.Net.Http, feel free to bring the code into your solution
