### ISSUE TITLE
[usage question] [help wanted] Creating stub for `private static readonly` field

### ISSUE THREAD

**Issue by hellboy81** [richardszalay/mockhttp#38]
See question on [so](https://stackoverflow.com/q/45152652/444079)

**Comment by richardszalay** [comment]
Hi there,

[Nkosi's answer on SO](https://stackoverflow.com/a/45154289/3603) pretty much covers the recommendation I would make, so I'll close this issue. Feel free to open a new issue if you have any further questions/issues/feature requests specific to MockHttp!

Richard
