### ISSUE TITLE
HttpClient and HttpResponseHandler "Respond" extensions don't actually work properly

### ISSUE THREAD

**Issue by EffortlessFury** [richardszalay/mockhttp#39]
https://github.com/richardszalay/mockhttp/commit/c70bf4f0744b7a233c66cecd493c67ad8e0850b6

Your tests directly invoke the "SendAsync" method of your custom handler, thus they pass; however, utilizing your custom handler within an HttpClient and attempting to pass the request to a different HttpClient/Handler will fail with the following error:

> The request message was already sent. Cannot send the same request message multiple times.

Am I not understanding the correct usage of these extension methods or is this an accidental oversight?

**Comment by richardszalay** [comment]
That's a really good point - I'd say it's an oversight.

Let me look into the HttpClient source to see if there's a logical way of working around the issue.

**Comment by richardszalay** [comment]
This has been fixed but is blocked by #41 as without that I can't get a release out.

**Comment by richardszalay** [comment]
This is fixed in 1.5.1 (just released)
