### ISSUE TITLE
Typo in obsolete message

### ISSUE THREAD

**Issue by leonard-thieu** [richardszalay/mockhttp#44]
> 
> MockedRequestExtensions.Respond(MockedRequest, HttpResponseMessage)' is obsolete: 'Using this overload is not recommended. Instead, use Response(req => new HttpResponseMessage(...))

`Response` should be `Respond`.

**Comment by richardszalay** [comment]
Woops, right you are. Will fix it when I make the next set of functional changes - otherwise, would happily accept a PR.

**Comment by richardszalay** [comment]
This was just released in 3.2.0
