### ISSUE TITLE
Support for "AnyTime-When"

### ISSUE THREAD

**Issue by EffortlessFury** [richardszalay/mockhttp#45]
Would you be opposed to adding support for defining loose "Whens" that can occur at any point during a test, not just after all the expects are complete? There are some perpetually occurring HTTP requests that can occur in the background during tests (depending on the service) that are non deterministic. It'd be nice if we could prepare for these cases.

**Comment by richardszalay** [comment]
Interesting. Maybe we could have an optional `WhenBehavior` enum as an argument to the MockHttpMessageHandler ctor, with values of `NoExpectations` (default) and `Always`.

This would still mean that expectations would still match before these whens if they both match the request, would that be acceptable?

**Comment by EffortlessFury** [comment]
Not sure if that entirely satisfies the circumstances I'm concerned about. Here's a step-by-step case example:

In the flow I'm executing, I expect requests A, B, and C to occur in the order given.

There is the possibility that request Z will fire off at any point in this flow. If it does, I want to define how to respond to it. Whether Z fires or not and regardless of when, I want the verification step to succeed if A, B, and C are all called in order and to fail if they were not.

**Comment by richardszalay** [comment]
The proposed solution works for the scenario you describe:

You would define A, B, and C via `Expect`; Z via `When`; and pass `BackendDefinitionBehavior.Always`to the constructor. 

A, B, and C would only only match in order, but Z would match anytime.

**Comment by EffortlessFury** [comment]
Ah I see, I understand your original message now. Yeah I don't see an issue with handling identical When and Expect definitions that way. Sounds like it'd work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by richardszalay** [comment]
This will be released in version 3.2.0 (see #50 to explain the major version bump). I'll update this issue when it's out.

**Comment by richardszalay** [comment]
This was just released in 3.2.0
