### ISSUE TITLE
Nuget Version issue in Visual Studio 2013

### ISSUE THREAD

**Issue by nadeemjamali** [richardszalay/mockhttp#51]
When installing the package **RichardSzalay.MockHttp** in a project using Visual Studio 2013's NuGet Package Manager, it throws the following error:

    Attempting to resolve dependency 'System.Net.Http (≥ 4.0.0)'.
    The 'System.Net.Http 4.0.0' package requires NuGet client version '3.0' or above, but the current 
    NuGet version is '2.12.0.817'.

When I try to upgrade NuGet client, I don't find any update in the Visual Studio Gallery! Even the latest version is 2.12.xx on [NuGet Official Page for VS 2013](https://marketplace.visualstudio.com/items?itemName=NuGetTeam.NuGetPackageManagerforVisualStudio2013).

Am I missing something?

**Comment by richardszalay** [comment]
Hi Nadeem,

It's difficult to continue supporting older versions of VS. The only thing I can advise is to attempt to install v1.2.1 of MockHttp, as that may not require you to have the System.Net.Http package installed.

Rich
