### ISSUE TITLE
Documentation does not display in Visual Studio

### ISSUE THREAD

**Issue by leonard-thieu** [richardszalay/mockhttp#52]
Using version 3.2.0 installed through NuGet.

Documentation does not display in Visual Studio even though it [exists in the source](https://github.com/richardszalay/mockhttp/blob/4e1818045f1f93c6ac115d67b3de9ccaa113bc10/RichardSzalay.MockHttp.Shared/MockHttpMessageHandlerExtensions.cs).

![devenv_2017-09-06_12-57-47](https://user-images.githubusercontent.com/5265970/30124460-3ceb5abc-9303-11e7-9d25-65a7f24d116e.png)

I believe this is because the XML documentation file is not distributed in the NuGet package. Could it be included so documentation can be displayed?

**Comment by richardszalay** [comment]
Thanks for reporting this. I've added the XML docs and released a new version of the NuGet package (v3.2.1)
