### ISSUE TITLE
.Net 461

### ISSUE THREAD

**Issue by kevinrjones** [richardszalay/mockhttp#55]
Hi RIchard,

I'm trying to use MockHttp in a .Net 4.6.1 project and I'm hitting an issue where there seems to be a clash of System.Net.http packages. I end up with one of two issues, either I can't install MockHttp as there is a clash with the version of System.Net.Http in the GAC, or I install both System.Net.Http and MockHttp from NuGet, run the test and get this:

[A]System.Net.Http.Headers.MeadiaTypeHeaderValue cannot be cast to [B]System.Net.Http.Headers.MeadiaTypeHeaderValue, which I guess means that it's trying to use two different versions of System.Net.Http.

I wondered if you'd seen this and if there's an easy fix?

Thanks

**Comment by richardszalay** [comment]
MockHttp takes a dependency on the System.Net.Http package as opposed to the System.Net.Http GAC assembly that shipped with netfx 4.6.1. This decision was mainly due to the NuGet package being updated regularly, and hence being a stronger long term bet than the GAC assembly.

Your choices are essentially:

1. Downgrade to MockHttp 1.2.2 in your test project
2. Move all of your projects (even your non-test ones) to use the System.Net.Http package

**Comment by kevinrjones** [comment]
Richard,

thanks for taking your time to reply to this. I've now added the System.Net.Http package to every project in the solution, even those that don't use it, and I'm still getting the same error. I've also tried to fallback to 1.2.2 and I'm getting 2 issues there, the same one with System.Net.Http and also problems trying to install BCL.

I'm wondering if I should clone the repo and build it on 4.6.1 and see if that works.

Thanks again

**Comment by richardszalay** [comment]
I've just tested:

1. Creating a simple net461 console app
2. `Install-Package System.Net.Http`
3. `Install-Package RichardSzalay.MockHttp`
4. Setting up a basic mock

And it ran as expected. I wonder if one of your assembly references is incorrect. Can you see if you can provide a minimal reproducible code snippet?

**Comment by kevinrjones** [comment]
I got to the bottom of the problem and it was my configuration. The project I'm testing and it's a .Net 4.6.1 project, however it references a couple of .Net Standard projects. Making both those .Net 4.6.1 projects fixed the issue.

Thanks for your time
