### ISSUE TITLE
Align with HttpClient multi-targeting recommendations

### ISSUE THREAD

**Issue by richardszalay** [richardszalay/mockhttp#61]
Based on: https://leastprivilege.com/2018/05/21/the-state-of-httpclient-and-net-multi-targeting/

Will require the following changes:

- Add a `.NetStandard2.0` target that only references `NETStandard.Library`
- Update the `.NETFramework4.5` target so that it has a `frameworkAssembly` rather than a `dependency`

The rest of the targets can remain as-is for compatibility, but since this will change the behavior for netfx45 we'll need to release it as a major/breaking version.

**Comment by YehudahA** [comment]
https://github.com/richardszalay/mockhttp/issues/36

**Comment by richardszalay** [comment]
Indeed! If only they'd published their recommendations sooner.

**Comment by richardszalay** [comment]
Released in 5.0.0
