### ISSUE TITLE
Do multiple Expects with a different WithContent

### ISSUE THREAD

**Issue by smato13** [richardszalay/mockhttp#62]
When you try to use the Expect Method with WithContent twice (with different content in WithContent for the 2 queries), the HttpClient mock only detects the first one implemented in the code and the second one isn't seen by calls.

**Comment by richardszalay** [comment]
I'm not able to reproduce this, see my test below. Are you aware that `Expect` sets up the requests to be called in the order that you mocked them (use `When` if that's not what you want). Failing that, if you can make me a failing test I'm happy to find the cause.

```csharp
public class Issue62Tests
{
    // https://github.com/richardszalay/mockhttp/issues/62
    [Fact]
    public async Task Can_expect_multiple_WithContent_requests()
    {
        var handler = new MockHttpMessageHandler();

        handler.Expect(HttpMethod.Post, "/")
            .WithContent("a")
            .Respond(new StringContent("a-result"));

        handler.Expect(HttpMethod.Post, "/")
            .WithContent("b")
            .Respond(new StringContent("b-result"));

        var client = new HttpClient(handler);

        var responseA = await client.PostAsync("http://tempuri.org/", new StringContent("a"));
        var responseB = await client.PostAsync("http://tempuri.org/", new StringContent("b"));

        var responseAContent = await responseA.EnsureSuccessStatusCode().Content.ReadAsStringAsync();
        var responseBContent = await responseB.EnsureSuccessStatusCode().Content.ReadAsStringAsync();

        Assert.Equal("a-result", responseAContent);
        Assert.Equal("b-result", responseBContent);
    }
}
```

**Comment by smato13** [comment]
The problem is that i'm trying to use your http mock with tests but even if i put my Expects in the right order, the first test gets all of its calls but the second gets a 404 error

my code : 

[Test]
        public async Task GivenLoginPassword_Connect()
        {
            // Arrange
            var pseudo = "user";
            var password = "user";

            var httpClientMock = new HttpClientFactoryMock();
            LoginService service = new LoginService(httpClientMock);

            IEnumerable<string> values;

            // Act
            bool result = await service.ConnectUser(pseudo, password);
           
            // Assert
            Assert.IsTrue(httpClientMock.HttpClient.DefaultRequestHeaders.TryGetValues("Authorization", out values));
            Assert.AreEqual(values.First(), "token");
            Assert.IsTrue(result);
        }

        [Test]
        public async Task GivenLoginPassword_WrongLoginInfos()
        {
            // Arrange
            var pseudo = "user2";
            var password = "user2";

            var httpClientMock = new HttpClientFactoryMock();
            LoginService service = new LoginService(httpClientMock);

            IEnumerable<string> values;

            // Act
            bool result = await service.ConnectUser(pseudo, password);


            // Assert
            Assert.IsFalse(result);
        }

        [Test]
        [Microsoft.VisualStudio.TestTools.UnitTesting.ExpectedException(typeof(Exception))]

        public async Task GivenLoginPassword_TokenReceivedEmpty()
        {
            // Arrange
            var pseudo = "user3";
            var password = "user3";

            var httpClientMock = new HttpClientFactoryMock();
            LoginService service = new LoginService(httpClientMock);

            IEnumerable<string> values;

            // Act
            bool result = await service.ConnectUser(pseudo, password);
        }

        [Test]
        public async Task GivenLoginPassword_TokenReceivedInvalid()
        {
            // Arrange
            var pseudo = "user4";
            var password = "user4";

            var httpClientMock = new HttpClientFactoryMock();
            LoginService service = new LoginService(httpClientMock);

            IEnumerable<string> values;

            // Act
            bool result = await service.ConnectUser(pseudo, password);


            // Assert
            Assert.IsTrue(httpClientMock.HttpClient.DefaultRequestHeaders.TryGetValues("Authorization", out values));
            Assert.AreEqual(values.First(), "wrongToken");
            Assert.IsFalse(result);
        }

**Comment by richardszalay** [comment]
There doesn't appear to be any use of MockHttp in that code. Can you create a small, standalone, reproducable sample?

**Comment by smato13** [comment]
excuse me that are my tests but i decided to use Expect but tests the content or the headers of my request inside of the Respond so i can respond what i want.
Sorry for taking your time but to make your package very efficient you should let people create several Expects and make your mock search for the right one no matter the order of call because that restricts a lot our use of it

**Comment by richardszalay** [comment]
@smato13 Change your uses of `Expect` to be `When` then it will work, as `When` will match in any order.

I'd recommend reading through the README carefully, as all of these use cases are documented there.

**Comment by smato13** [comment]
Ok i'll try thanks

**Comment by smato13** [comment]
Thanks it works better when you use the right thing. Sorry for bothering you for nothing :/

**Comment by richardszalay** [comment]
@smato13 No worries, glad I could help!

**Comment by smato13** [comment]
And thanks for your reactivity by the way !! :) 👍
