### ISSUE TITLE
System.NullReferenceException trying to return a null response

### ISSUE THREAD

**Issue by dday4thedeceiver** [richardszalay/mockhttp#64]
Trying to test the case when httpClient returns null:

```
var mockHttp = new MockHttpMessageHandler();
mockHttp.Fallback.Respond(() => Task.FromResult<HttpResponseMessage>(null));
var r = mockHttp.ToHttpClient().GetAsync("http://a").Result;
```

...throws a null reference exception.

**Comment by dday4thedeceiver** [comment]
I don't believe it does under Windows but I've seen reports on Android, it was more completeness/exploratory testing

**Comment by richardszalay** [comment]
No problem. I'll happy accept a PR (with tests!) if you're willing/able, otherwise I'll tackle it next time I make changes to the project.

**Comment by richardszalay** [comment]
If you can provide a repro scenario where this actually happens on Android, making sure that it's not actually `response.Content` that's null, then I'm happy to add support myself.

**Comment by guibirow** [comment]
I don't think `HttpResponseMessage` can be null.

In general, it should return a response with the result for the request, to describe:
- the response status code (if it was successful)
- the content (That could probably be null in this case or an empty stream)

**Comment by richardszalay** [comment]
I'm going to close this issue. If you can find a real world scenario where this can happen I'm happy to add support
