### ISSUE TITLE
Sign the assembly in the nuget.org package?

### ISSUE THREAD

**Issue by Huffers** [richardszalay/mockhttp#65]
Hi,

Would it be possible to sign the assemblies in the RichardSzalay.MockHttp package on nuget.org?

This would make it easier for more people to use, in case their build & test pipelines require strong-named assemblies.

There's a MockHttpSigned package on nuget.org, however the origin of that package is a little unclear and it hasn't been updated since MockHttp 1.2.1 (in 2015).

Thanks,

Andrew Huff

**Comment by richardszalay** [comment]
Hi Andrew,

I'm happy to oblige in theory. 

Could you see if you can find official guidance on signing assemblies and it's impact on backward compatibility and platform support? Specifically I need to make sure it will work with upgraders on everything from .NET Core to Xamarin Android.

Richard

**Comment by Huffers** [comment]
I've done some research and found this issue is much less clear cut than I expected, with some [potential back-compatibility issues](https://github.com/xamarin/AndroidSupportComponents/issues/54), and heated debates on whether the best practice is to strong-name sign or not. As a result, I'm withdrawing my request. Thank you for your quick response though!
