### ISSUE TITLE
WithContent, WithJsonContent and WithJsonSerializedContent extensions

### ISSUE THREAD

**Issue by patros** [richardszalay/mockhttp#69]
Hi,

I created an extension package a while ago to make my life easier. Long story short, I needed to check the content type was correctly set. Just wondering if you have any interest in a pull request for all/some of what I implemented.

The project is here [https://github.com/patros/mockhttp-extensions](https://github.com/patros/mockhttp-extensions).

In short it adds these methods...

```
.WithContent(string contentType, string content)
.WithJsonContent(string json)
.WithJsonContent(object obj)
```

**Comment by richardszalay** [comment]
Apologies for the delay, and thanks for the PR.

However, I'm going to decline this simply because I don't want to introduce new dependencies to things like JSON.NET. Hope you understand!

**Comment by patros** [comment]
@richardszalay completely understand. Thanks for your awesome library!

**Comment by coderpatros** [comment]
@richardszalay wondering if you would accept a PR for this now. Assuming I update it to use `System.Text.Json` instead.
