### ISSUE TITLE
RequestMessage is not set on HttpResponseMessage

### ISSUE THREAD

**Issue by oschwald** [richardszalay/mockhttp#7]
In the process of testing some code, I received some confusing null reference exceptions in code paths that were known to work without the mocking. It turns out this was because mockhttp does not set the `RequestMessage` on `HttpResponseMessage`.

**Comment by richardszalay** [comment]
Thanks for taking the time to report this. I've fixed it and pushed out 1.2.1 to NuGet.

**Comment by oschwald** [comment]
Thanks!
