### ISSUE TITLE
Expect, but expect any order

### ISSUE THREAD

**Issue by philals** [richardszalay/mockhttp#71]
Hi

Thanks for making this lib.

Would be cool if there was an .ExpectInAnyOrder(). 

It works the same as Expect() but does not assert ordering. This would allow more refactoring of backend ordering.

Thanks

**Comment by philals** [comment]
Other method names I could thing of:

1. ExpectUnordered
2. Expect(...normalParam, true)

**Comment by richardszalay** [comment]
Depending on what functionality you want from `Expect`:

If you simply want unordered matching, use `When`.

If you still want to assert that an unordered request was invoked, you can use `GetMatchCount`:

```
var mockHttp = new MockHttpMessageHandler();

var request = mockHttp.When("http://localhost/api/user/*")
        .Respond("application/json", "{'name' : 'Test McGee'}");

var client = mockHttp.ToHttpClient();

await client.GetAsync("http://localhost/api/user/1234");

Assert.Equal(1, mockHttp.GetMatchCount(request));
```

**Comment by philals** [comment]
Cheers. 

Looks like match count will satisfy what I'm after. Thanks for pointing it out.
