### ISSUE TITLE
Does this not work with Windows 10? 

### ISSUE THREAD

**Issue by prabodhprakash** [richardszalay/mockhttp#74]
Just went through readme and found no mention of windows 10 -- given that the library was recently updated, I am wondering, if it really does not work with windows 10?

**Comment by Skattered** [comment]
MockHttp is compiled for .NET Standard 2.0, .NET Standard 1.1, .NET 4, and .NET 4.5, **as well a Portable Class Library (Profile 328) supporting**:

The OS list is just for that format. If you using it with any of the .net standard/framework versions it will work anywhere they are supported.

**Comment by richardszalay** [comment]
@Skattered is correct: mockhttp targets various .NET incarnations, so any operating system that supports one of those is indirectly supported.

I develop mockhttp on Windows 10, so that's certainly supported 😄
