### ISSUE TITLE
please add wiki 

### ISSUE THREAD

**Issue by behroozbc** [richardszalay/mockhttp#77]
hi 
please add wiki for your package

**Comment by richardszalay** [comment]
Hi, what would you like to see in the wiki that isn't covered by the README?

**Comment by behroozbc** [comment]
No 
add one thing for old version documents

**Comment by richardszalay** [comment]
I'm sorry, I don't understand. I believe the README contains sufficient information to use the library. If you let me know if anything is missing or difficult to understand I'm happy to make improvements.

I'll close this issue for now.
