### ISSUE TITLE
I'm unable to set the base address when using IHttpClientFactory?

### ISSUE THREAD

**Issue by sonic1981** [richardszalay/mockhttp#81]
I'm using a namedHttpClient using .Net Core 3.1:

```c#
builder.Services.AddHttpClient("LoginApp", h =>
            {
                h.BaseAddress = new Uri($"https://${Environment.GetEnvironmentVariable("URL")}");
            });
```

So the base address is setup in the DI framework. There is no way to set the `BaseAddress` when calling `ToHttpClient` so I end up with an error when calling `PostAsync`:

> An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set

Looking at th HttpClient returned from the mock it does not have a `BaseAddress` set. I can't see a good way to set this property using this framework accept to do:

```c#
HttpClient httpClient = mockHttpHandler.ToHttpClient();
httpClient.BaseAddress = new Uri("https://ci1-sfc.ivanticlouddev.com");
```

I think it should be quite straight forward to add an overload to `ToHttpClient` accepting a base address string?

**Comment by sonic1981** [comment]
I'm not sure if `ToHttpClient` is the best place to put this... Maybe it is best to just set the property in the test like I am?

**Comment by alexrosenfeld10** [comment]
FWIW, I have the same issue
