### ISSUE TITLE
NullReferenceException if response is not configured.

### ISSUE THREAD

**Issue by perfectsquircle** [richardszalay/mockhttp#87]
If a request is configured, but a response is never configured, a NullReferenceException is thrown when SendAsync is called on the HTTP client. This is confusing to the user and takes some time to unravel what went wrong.

```csharp
mockHttp.Expect("/foo")
        .WithQueryString("bar", "bat")
        .WithQueryString("fizz", "buzz");
        // forgot to configure response

httpClient.GetAsync("/foo"); // throws NullReferenceException.
```

**Comment by 0x326** [comment]
I actually just ran into this myself, so I can confirm.

**Comment by FroggieFrog** [comment]
@richardszalay Is there any chance of a new release on Nuget with this fix included?

**Comment by richardszalay** [comment]
Verion 7.0.0 includes this change.
