### ISSUE TITLE
Can't Match Using WithFormData, WithHeaders

### ISSUE THREAD

**Issue by bobbyg603** [richardszalay/mockhttp#97]
I'm trying to write a test that an endpoint gets called with the correct URL and FormData containing email and password:

```
[Test]
public void BugSplatApiClient_Authenticate_ShouldCallPostAsyncWithUrlAndFormData()
{
    var email = "fred";
    var password = "******";
    var expectedUri = new Uri("https://app.bugsplat.com/api/authenticatev3");
    var headers = new List<KeyValuePair<string, string>>() { 
        new KeyValuePair<string, string>(
            "Set-Cookie",
            "xsrf-token:abc123; some-other-cookie:xyz321"
        )
    };
    var mockHttp = new MockHttpMessageHandler();
    Console.WriteLine(expectedUri.ToString());
    mockHttp
        .Expect(HttpMethod.Post, expectedUri.ToString())
        .WithFormData("email", email)
        .WithFormData("password", password)
        .Respond(HttpStatusCode.OK, headers, new StringContent(""));
    var httpClient = mockHttp.ToHttpClient();
    var httpClientFactory = CreateFakeHttpClientFactory(httpClient);
    var sut = new BugSplatApiClient(email, password, httpClientFactory);
    
    var result = sut.Authenticate().Result;
    
    mockHttp.VerifyNoOutstandingExpectation();
}
```

But unfortunately `mockHttp` hits the fallback and returns 404 in the `Authenticate` function:

```
public async Task<HttpResponseMessage> Authenticate()
{
    var url = new Uri(Host, "/api/authenticatev3");
    var formData = new MultipartFormDataContent()
    {
        { new StringContent(email), "email" },
        { new StringContent(password), "password" }
    };

    var authenticateResponse = await this.httpClient.PostAsync(url, formData);

    Console.WriteLine(authenticateResponse);

    ThrowIfHttpRequestFailed(authenticateResponse);

    var setCookieHeader = authenticateResponse.Headers.FirstOrDefault(header => header.Key.Contains("Set-Cookie")).Value;
    var xsrfCookie = setCookieHeader.FirstOrDefault(value => value.Contains("xsrf-token"));
    var xsrfToken = xsrfCookie.Split(';').First().Split('=').Last();
    this.httpClient.DefaultRequestHeaders.Add("xsrf-token", xsrfToken);
    this.Authenticated = true;

    return authenticateResponse;
}
```

Unfortunately my .NET coreCLR debugger stopped attaching a few days ago on my m1 and I haven't been able to do much investigation.

Is there something obvious that I'm doing wrong? The MultipartFormDataContent piece in Authenticate appears very similar to the example in the tests. Additionally, when I comment out the calls to `WithFormData` everything works fine.

Thanks for any help that can be provided!

**Comment by bobbyg603** [comment]
I just tried a similar things with `WithHeaders` and that doesn't appear to work either :(

**Comment by richardszalay** [comment]
Hi @bobbyg603 thanks for logging this. It looks like there is indeed a compatibility issue with `WithFromData` and the way you are submitting your content. I'll have a look at fixing that issue, but in the meantime you can send your data like this if it's acceptable for your usecase:

```
var formData = new MultipartFormDataContent()
{
    new FormUrlEncodedContent(new Dictionary<string, string>
    {
         ["email"] = email,
         ["password"] = password
    })
};
```

Can you provide a repro for the `WithHeaders` issue you're having?

**Comment by richardszalay** [comment]
Hi again @bobbyg603 - I might close this issue soon if I don't hear back from you. If you do manage to repro the issue again, open another issue can we can go through it.

**Comment by bobbyg603** [comment]
Hi @richardszalay I've had to move on to other projects. Next time I'm working on the project I'll try and create a reproducible example unfortunately I don't have a good ETA.

**Comment by richardszalay** [comment]
No problem, I'll close this issue then. Feel free to reopen it in the future if you run into it again!
